collections_dir: user_collections
collections:
        album_1:
                output: true
        album_2:
                output: true

theme: jekyll-theme-minimal
title: denpa.nekomimifan.club
description: Everything is better with cat ears.
logo: /icons/android-chrome-512x512.png
show_downloads: false
